name: terraform workflow

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      client_id: ${{ secrets.ARM_CLIENT_ID }}
      client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      tenant_id: ${{ secrets.ARM_TENANT_ID }}
      subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
      vms_password: ${{ secrets.VM_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        name: setup terraform

      - name: change dir
        run: cd tf

      - name: init
        run: terraform init

      - name: plan
        run: terraform plan

      - name: apply
        run: terraform apply -auto-approve