name: terraform workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      client_id: ${{ secrets.ARM_CLIENT_ID }}
      client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      tenant_id: ${{ secrets.ARM_TENANT_ID }}
      subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
      vms_password: ${{ secrets.VM_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        name: setup terraform

      - name: terraform init
        run: terraform init
        working-directory: tf

      - name: terraform plan
        run: terraform plan
        working-directory: tf

      - name: terraform apply
        run: terraform apply -auto-approve
        working-directory: tf
